spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  # mybatis-plus
mybatis-plus:
  #  config-locations: classpath*:com/geek/**/*.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/geek/**/*.xml

# logging.level 后面是包名，表示该包下的日志级别
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info
    com:
      geek:
        debug

